# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycode',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='classificationappliedfor',
            name='primary_certificate_authority',
            field=models.ForeignKey(db_column='certifying_org_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='registries.Organization', verbose_name='Certifying Organization'),
        ),
        migrations.AlterField(
            model_name='contactat',
            name='contact_tel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact telephone number'),
        ),
        migrations.AlterField(
            model_name='contactat',
            name='org',
            field=models.ForeignKey(db_column='org_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='registries.Organization', verbose_name='Company Reference'),
        ),
        migrations.AlterField(
            model_name='contactat',
            name='person',
            field=models.ForeignKey(db_column='person_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='registries.Person', verbose_name='Person Reference'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='fax_tel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Facsimile telephone number'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='main_tel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Company main telephone number'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='province_state',
            field=models.ForeignKey(db_column='province_state_guid', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwells.ProvinceState', verbose_name='Province/State'),
        ),
    ]
